# Generated by Django 2.2 on 2019-04-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_auto_20190415_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='humidity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='water',
            field=models.IntegerField(default=0),
        ),
    ]
